---
title: "Main"
author: "Pak Kin Lai, pl2599"
date: "4/6/2018"
output: pdf_document
---
```{r, warning = FALSE}

if(!require("ggplot2")){
  install.packages("ggplot2")
}

library(ggplot2)
```


### Step 0: Specify Directories and Source

```{r wkdir}
setwd("~/Documents/GitHub/project-4-open-project-group3/doc") 
source("../lib/functions.R")
```

### Step 1: Setup Controls

```{r setup, echo=FALSE}
run_visual <- F
read_data <- F
process_data <- F
create_models <- F
make_pred <- F
calc_RMSE <- F
sum_RMSE <- T
run_LR <- T
run_LR_PCA <- T
```

### Step 2: Load Data and Make Features

```{r}
# if(read_data)
# {
#   train <- read.csv("../data/training.csv", as.is = TRUE, header = TRUE)
#   #test <- read.csv("../data/testing.csv", as.is = TRUE, header = TRUE)
#   test <- train[(nrow(train)- 49999):nrow(train),]
#   save(train, file = "../output/train.Rdata")
#   save(test, file = "../output/test.Rdata")
#   
# }

load("../output/sample_train.RData")
load("../output/sample_test.RData")
```


### Step 2.5: Data Visualization

```{r}
if(run_visual)
{
  #Creates the vwap visuals
  sample_train$security_id <- factor(sample_train$security_id)
  vwap_train <- ggplot(sample_train, aes(x = security_id, y = trade_vwap, color = trade_vwap)) + geom_point() +     scale_color_gradient(low = "lightgreen", high = "darkblue") + 
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
  vwap_train
  ggsave("../figs/vwap_train.png")
  
  
  vwap_test <- ggplot(sample_test, aes(x = security_id, y = trade_vwap, color = trade_vwap)) + geom_point() +     scale_color_gradient(low = "lightgreen", high = "darkblue") + 
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
  vwap_test
  ggsave("../figs/vwap_test.png")
  
  #Creates the price visuals for security 25, 50, 75, and 100
  subset_train <- sample_train[sample_train$security_id == 25 | sample_train$security_id == 50 | sample_train$security_id == 75 | sample_train$security_id == 100,]
  subset_test <- sample_test[sample_test$security_id == 25 | sample_test$security_id == 50 |
                                sample_test$security_id == 75 | sample_test$security_id == 100,]
  
  #Dataframes separated to bid and ask prices
  train_price_bid <- data.frame(NA, nrow = 400, ncol = 3)
  colnames(train_price_bid) <- c("Security_Id", "Event_t", "Price")
  train_price_ask <- data.frame(NA, nrow = 400, ncol = 3)
  colnames(train_price_ask) <- c("Security_Id", "Event_t", "Price")
  
  #Temp dataframes to be added to the main dataframes.
  train_price_bid_temp <- data.frame(NA, nrow = 100, ncol = 3)
   colnames(train_price_bid_temp) <- c("Security_Id", "Event_t", "Price")
   
   train_price_ask_temp <- data.frame(NA, nrow = 100, ncol = 3)
   colnames(train_price_ask_temp) <- c("Security_Id", "Event_t", "Price")
  
  #Security 25
  for(i in 1:50)
  {
    train_price_bid[i, 1] <- 25
    train_price_bid[i, 2] <- i
    train_price_bid[i, 3] <- colMeans(subset_train[subset_train$security_id == 25, 6 + i*4])
    train_price_ask[i, 1] <- 25
    train_price_ask[i, 2] <- i
    train_price_ask[i, 3] <- colMeans(subset_train[subset_train$security_id == 25, 7 + i*4])
  }
  for(i in 51:100)
  {
    train_price_bid[i, 1] <- 25
    train_price_bid[i, 2] <- i
    train_price_bid[i, 3] <- colMeans(subset_train[subset_train$security_id == 25, 106 + i*2])
    train_price_ask[i, 1] <- 25
    train_price_ask[i, 2] <- i
    train_price_ask[i, 3] <- colMeans(subset_train[subset_train$security_id == 25, 107 + i*2])
  }
  
  #Security 50
  for(i in 1:50)
  {
    train_price_bid_temp[i, 1] <- 50
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 50, 6 + i*4])
    train_price_ask_temp[i, 1] <- 50
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 50, 7 + i*4])
    
  }
  for(i in 51:100)
  {
    train_price_bid_temp[i, 1] <- 50
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 50, 106 + i*2])
    train_price_ask_temp[i, 1] <- 50
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 50, 107 + i*2])
  }
   
   train_price_bid <- rbind(train_price_bid, train_price_bid_temp)
   train_price_ask <- rbind(train_price_ask, train_price_ask_temp)
   
   #Security 75
   for(i in 1:50)
  {
    train_price_bid_temp[i, 1] <- 75
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 75, 6 + i*4])
    train_price_ask_temp[i, 1] <- 75
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 75, 7 + i*4])
    
  }
  for(i in 51:100)
  {
    train_price_bid_temp[i, 1] <- 75
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 75, 106 + i*2])
    train_price_ask_temp[i, 1] <- 75
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 75, 107 + i*2])
  }
   
  train_price_bid <- rbind(train_price_bid, train_price_bid_temp)
  train_price_ask <- rbind(train_price_ask, train_price_ask_temp)

  #Security 100
  for(i in 1:50)
  {
    train_price_bid_temp[i, 1] <- 100
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 100, 6 + i*4])
    train_price_ask_temp[i, 1] <- 100
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 100, 7 + i*4])
    
  }
  for(i in 51:100)
  {
    train_price_bid_temp[i, 1] <- 100
    train_price_bid_temp[i, 2] <- i
    train_price_bid_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 100, 106 + i*2])
    train_price_ask_temp[i, 1] <- 100
    train_price_ask_temp[i, 2] <- i
    train_price_ask_temp[i, 3] <- colMeans(subset_train[subset_train$security_id == 100, 107 + i*2])
  }
   
  train_price_bid <- rbind(train_price_bid, train_price_bid_temp)
  train_price_ask <- rbind(train_price_ask, train_price_ask_temp)
  
  
  
  train_price_bid_plot <- ggplot(train_price_bid, aes(x = Event_t, y = Price, color = factor(Security_Id))) + geom_line() + 
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) + facet_wrap( ~ Security_Id, ncol = 2, scales = "free") + guides(color = guide_legend(title = "Security ID"))
  
  train_price_ask_plot <- ggplot(train_price_ask, aes(x = Event_t, y = Price, color = factor(Security_Id))) + geom_line() + 
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) + facet_wrap( ~ Security_Id, ncol = 2, scales = "free") + guides(color = guide_legend(title = "Security ID"))

  train_price_bid_plot
  ggsave("../figs/price_bid_train.png")
  train_price_ask_plot
  ggsave("../figs/price_ask_train.png")
}
```

### Step 3: Process Data

```{r}
# if(process_data)
# {
#   if(run_LR)
#   {
#     train_LR <- LR_data_process(sample_train)
#     save(train_LR, file = "../output/train_LR.Rdata")
#   }
# }

```

### Step 4: Create Models

```{r}
if(create_models)
{
  if(run_LR)
  {
    #load("../output/train_LR.RData")

    #LR_models <- create_LR_models(train_LR)
    LR_models <- create_LR_models(sample_train)
    save(LR_models, file = "../output/LR_models.RData")
  }
  if(run_LR_PCA)
  {
    load("../output/train_pca.RData")
    load("../output/test_pca.RData")
    LR_PCA_models <- create_LR_PCA_models(sample_train, train_pca)
    save(LR_PCA_models, file = "../output/LR_PCA_models.RData")
  }
}
```

### Step 5: Make Predictions

```{r}
if(make_pred)
{
  if(run_LR)
  {
    load("../output/LR_models.RData")
    
    LR_predictions <- make_LR_predictions(LR_models, sample_test)
    save(LR_predictions, file = "../output/LR_predictions.RData")
  }
  if(run_LR_PCA)
  {
    load("../output/LR_PCA_models.RData")
    LR_PCA_predictions <- make_LR_PCA_predictions(LR_PCA_models, sample_test, test_pca)
    save(LR_PCA_predictions, file = "../output/LR_PCA_predictions.RData")
    
  }
}
```

### Step 6: Calculate RMSE

```{r}
if(calc_RMSE)
{
  if(run_LR)
  {
    load("../output/LR_predictions.RData")
    LR_RMSE <- evaluate_RMSE(LR_predictions, sample_test)
    save(LR_RMSE, file = "../output/LR_RMSE.RData")
  }
  if(run_LR_PCA)
  {
    load("../output/LR_PCA_predictions.RData")
    LR_PCA_RMSE <- evaluate_RMSE(LR_PCA_predictions, sample_test)
    save(LR_PCA_RMSE, file = "../output/LR_PCA_RMSE.RData")
  }
}

```


### Step 7: Summarize RMSE

```{r}
if(sum_RMSE)
{
  if(run_LR)
  {
    load("../output/LR_RMSE.RData")
    cat("RMSE for LR Model =", LR_RMSE, "\n")
  }
  if(run_LR_PCA)
  {
    load("../output/LR_PCA_RMSE.RData")
    cat("RMSE for LR_PCA Model =", LR_PCA_RMSE, "\n")
  }
  
}
```